### ISSUE TITLE
 al_hide_mouse_cursor is missing from allegro-sys

### ISSUE THREAD

**Issue by ZackGabri** [SiegeLord/RustAllegro#17]
So i was looking on a way to hide the cursor in the allegro docs, found al_hide_mouse_cursor, tried looking for something similar in the rust wrapper, couldn't find it, so i looked at the allegro-sys crate, and couldn't even find it there, tried adding it manually in the `mouse.rs` file then using that local version of the sys crate but because it doesn't allow me to use the returned pointer from the allegro wrapper because it's a "different version of the crate" it required me to change allegro and the other addons to local versions as well, it's really messy that i had to do all of that just for a missing method

**Comment by SiegeLord** [comment]
Yeah, aside from merging everything into one crate as #15 suggests you basically need to switch all the interdependent crates to the local versions.
