### ISSUE TITLE
How do I force static monolith linking?

### ISSUE THREAD

**Issue by SeanTolstoyevski** [SiegeLord/RustAllegro#18]
Hi,
Since I'm a Windows user, I don't want to mess with dll's.
Instead I created the allegro as a monolith.
Now how can I tell Rust to use this library?

**Comment by SiegeLord** [comment]
This wrapper doesn't have this feature built-in (I suppose it could be), but you can specify the `link_none` feature (see https://doc.rust-lang.org/cargo/reference/features.html#dependency-features) and then add a `build.rs` [script](https://doc.rust-lang.org/cargo/reference/build-scripts.html) to your crate with something like this in it:

```
fn main() {
    println!("cargo:rustc-link-lib=-l allegro_monolith_static");
    println!("cargo:rustc-link-search=-L DIRECTORY_WITH_LIBRARY");
}
```

Note that you'll need to also specify a whole bunch of system libraries (all the ones [here](https://github.com/liballeg/allegro_winpkg/blob/master/universal/AllegroDeps.targets#L24) and [here](https://github.com/liballeg/allegro_winpkg/blob/master/universal/Allegro.targets#L53)] to link to as well using the same mechanism.
