### ISSUE TITLE
draw_prim - the trait bound is not satisfied

### ISSUE THREAD

**Issue by ccie18473** [SiegeLord/RustAllegro#20]
Hello Team,
I noticed that for my scenario draw_pixel and put_pixel are very slow so I decided to try Allegro Primitives.

This is what I'm trying:
######################
let mut vtx: Vertex = Vertex { x: 0.0, y: 0.0, z: 0.0, u: 0.0, v: 0.0, color: Color::from_rgb(0,0,0) };
let mut vtxs : Vec<Vertex> = Vec::new();

    for y in 0..SCREEN_HEIGHT {
        for x in 0..SCREEN_WIDTH {
            let color = screen_buffer[x + SCREEN_WIDTH * y];
            vtx.x = x as f32;
            vtx.y = y as f32;
            vtx.z = 0.0;
            vtx.u = 0.0;
            vtx.v = 0.0;
            vtx.color = color;
            vtxs.push(vtx);
            
        }
    }

    let back = display.get_backbuffer();
    core.set_target_bitmap(Some(back));
    primitives.draw_prim(&vtxs, Some(back), 0, vtxs.len() as u32, PrimType::PointList);
######################
But I get:
the trait bound `Vec<allegro_primitives::Vertex>: VertexSource` is not satisfied
the trait `VertexSource` is implemented for `[T]

And I have no idea how to solve this. Can you please point me to the right direction ?

Thanks

**Comment by ccie18473** [comment]
I was able to find an workaround:

//g.primitives.draw_prim(&vtxs, Some(back), 0, vtxs.len() as u32, PrimType::PointList);

    let back_ptr = back.get_allegro_bitmap();
    unsafe {
        al_draw_prim(
            vtxs.as_ptr() as *const libc::c_void,
            ptr::null(),
            back_ptr as *mut ALLEGRO_BITMAP,
            0,
            vtxs.len() as i32,
            PrimType::PointList as i32,
        )
    };

But this method is slow as when using put_pixel or draw_pixel. Is there any way to get fast pixel operations ?

Thanks.

**Comment by SiegeLord** [comment]
The way to solve the error is to slice the vector `&vxts[...]`. What are you trying to accomplish? Drawing a point per pixel is not super efficient in general.

**Comment by ccie18473** [comment]
Thanks for the feedback. I'm trying to port one old arcade game and it uses this kind of bitmap operations. In the meanwhile I got rid of the slowness of put_pixel and draw_pixel implementing al_lock_bitmap/al_unlock_bitmap. The wrapping wasn't done for some reason ?

**Comment by SiegeLord** [comment]
Ah, okay. Yeah, lock/unlock is the way to go. Ideally you'd also use a shader to speed it up further if possible.

**Comment by ccie18473** [comment]
Vertex issue solved, use slice &vtxs[..].
