### ISSUE TITLE
Stream write_fragment

### ISSUE THREAD

**Issue by ccie18473** [SiegeLord/RustAllegro#21]
Team,

I'm trying to use write_fragment but I don't get why this isn't working:

===================
type write_cb_fn<'a> = &'a mut dyn FnMut(&mut dyn Write);

pub fn push_sample(game: &mut game, sample: i16) {
    println!("push_sample");

    let write_cb: write_cb_fn;
    let mut cb = |buf: &mut dyn Write| {
        buf.write(&mut [sample as u8]).unwrap();
        println!("This is the callback");
    };
    write_cb = &mut cb;

    let result = game.stream.write_fragment(write_cb);
    println!("result:{:?}", result);
}

===================

It prints "This is the callback" but never prints the "result". It seems it runs the callback but hangs right after that,
What am I missing here? Any pointers welcome.

Thanks.

**Comment by SiegeLord** [comment]
Thanks, it's a bug. https://github.com/SiegeLord/RustAllegro/pull/23 should fix it.

**Comment by ccie18473** [comment]
Thanks for taking care of this. When can I expect to test this change ?

**Comment by SiegeLord** [comment]
Should be live in version 0.0.45
