### ISSUE TITLE
Mixer vs Sink

### ISSUE THREAD

**Issue by ccie18473** [SiegeLord/RustAllegro#22]
Team,

Sorry if this sounds basic but I can't understand why sink works and mixer doesn't:

============
fn main() {

    let core = Core::init().unwrap();
    let audio = AudioAddon::init(&core).unwrap();
    let codec = AcodecAddon::init(&audio).unwrap();
    let mut mixer = Mixer::new(&audio).unwrap();
    let mut sink = Sink::new(&audio).unwrap();

    let mut stream = AudioStream::load(&audio, "beginning.wav").unwrap();
    //stream.attach(&mut sink).unwrap(); <-- works
    stream.attach(&mut mixer).unwrap();
    stream.set_playmode(Playmode::Once).unwrap();

    core.rest(5.0);
}

============
To be honest, I don't even get what sink means but I understood the logic from the audio_example.rs.

Thanks.

**Comment by SiegeLord** [comment]
A Sink is connected to the system's audio API, and conceptually is the object that actually produces audio output. A Mixer combines ("mixes") one or more audio sources into one, but unless attached (directly or via another mixer) to a Sink, it won't produce audio output. A Sink can also combine multiple outputs, so typically you don't need a separate Mixer. Mixers are handy to implement things like SFX/Music/etc sliders in games.

**Comment by ccie18473** [comment]
Thank you for the explanation.
